apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: my-console-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: my-console-app
  policy:
    semver:
      range: 1.x.x
